version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  short:
    format: '%(asctime)s,%(msecs)03d [%(name)s]:%(message)s'
    datefmt: '%H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: short
    stream: ext://sys.stdout
  error:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stderr
  file:
    class : logging.handlers.RotatingFileHandler
    formatter: simple
    filename: logconfig.log
    maxBytes: 1024
    backupCount: 3
  email:
    class: logging.handlers.SMTPHandler
    mailhost: localhost
    fromaddr: my_app@domain.tld
    toaddrs:
      - support_team@domain.tld
      - dev_team@domain.tld
    subject: Houston, we have a problem.
loggers:
  debug:
    level: DEBUG
    handlers: [console]
    propagate: no
  info:
    level: DEBUG
    handlers: [console]
    propagate: no
  threat:
    level: DEBUG
    handlers: [console]
    propagate: no
  error:
    level: DEBUG
    handlers: [error]
    propagate: no
  notif:
    level: DEBUG
    handlers: [email]
    propagate: no

root:
  level: DEBUG
  handlers: [console]