version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  short:
    format: '%(asctime)s,%(msecs)03d [%(name)s]:%(message)s'
    datefmt: '%H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: short
    stream: ext://sys.stdout
  errorstream:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stderr
  genfile:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: logs/general_logs.log
    maxBytes: 10485760 # 10MB
    backupCount: 5
    encoding: utf8
  eventfile:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: logs/events.log
    maxBytes: 10485760 # 10MB
    backupCount: 2
    encoding: utf8
  email:
    class: logging.handlers.SMTPHandler
    mailhost: localhost
    fromaddr: my_app@domain.tld
    toaddrs:
      - support_team@domain.tld
      - dev_team@domain.tld
    subject: Houston, we have a problem.
loggers:
  debug:
    level: DEBUG
    handlers: [genfile]
    propagate: no
  info:
    level: DEBUG
    handlers: [genfile]
    propagate: no
  error:
    level: ERROR
    handlers: [errorstream, genfile]
    propagate: no
  errorfile:
    level: ERROR
    handlers: [genfile]
    propagate: no
  cli:
    level: DEBUG
    handlers: [console]
    propagate: no
  threats:
    level: DEBUG
    handlers: [eventfile]
    propagate: no
  modifs:
    level: DEBUG
    handlers: [eventfile]
    propagate: no
  mail:
    level: DEBUG
    handlers: []
    propagate: no

root:
  level: DEBUG
  handlers: [console]